[package]
name = "scarab-db-postgres"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
scarab-engine = { workspace = true }
async-trait = { workspace = true }
sqlx = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
