/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The most recent runs, newest first — the runs-list view (ADR-0013, 0028). */
        get: operations["list_runs"];
        put?: never;
        /** Create and durably persist a new run from an inline pipeline. */
        post: operations["create_run"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current status of a run and its steps. */
        get: operations["get_run"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Server-Sent-Events tail of the run's append-only event log — the status
         *     timeline (ADR-0013): RunCreated, transitions, attempt start/finish.
         */
        get: operations["get_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{id}/gates/{step}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Release a manual gate, resuming its suspended run (ADR-0008, 0032). Authz'd
         *     as a write; exactly-once (a repeat approve is a no-op).
         */
        post: operations["approve_gate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{id}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Server-Sent-Events of step **log bodies** (ADR-0013): replays every
         *     committed chunk (decompressed from the object store, indexed by Postgres
         *     offsets), then — while the run is still going — live-tails new chunks via the
         *     log pipeline's broadcast. A terminal run yields the full log and closes.
         */
        get: operations["get_logs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{id}/steps/{step}/restart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restart a step and its transitive descendants (ADR-0027 smart invalidation):
         *     the target and every step depending on it are re-armed and re-run in
         *     dependency order; siblings and ancestors are left as-is.
         */
        post: operations["restart_step"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description `POST /v1/runs` body: an inline pipeline to run immediately. */
        CreateRunRequest: {
            pipeline: components["schemas"]["PipelineDto"];
        };
        CreateRunResponse: {
            id: string;
            status: string;
        };
        /** @description The inline pipeline (IR subset). */
        PipelineDto: {
            /**
             * Format: int32
             * @description IR schema version (ADR-0022).
             */
            ir_version: number;
            steps: components["schemas"]["StepDto"][];
        };
        /** @description `GET /v1/runs` body: the most recent runs, newest first. */
        RunListResponse: {
            runs: components["schemas"]["RunSummaryDto"][];
        };
        RunStatusResponse: {
            id: string;
            status: string;
            steps: components["schemas"]["StepStatusDto"][];
        };
        /** @description One run in the list view: identity, status, and creation time (epoch millis). */
        RunSummaryDto: {
            /** Format: int64 */
            created_at: number;
            id: string;
            status: string;
        };
        /** @description One step (IR subset): the step contract is an OCI `image` + `command`. */
        StepDto: {
            command?: string[];
            env?: {
                [key: string]: string;
            };
            id: string;
            image: string;
            needs?: string[];
        };
        StepStatusDto: {
            attempts: number;
            id: string;
            status: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_runs: {
        parameters: {
            query?: {
                /** @description max runs to return (default 50, max 200) */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunListResponse"];
                };
            };
        };
    };
    create_run: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRunRequest"];
            };
        };
        responses: {
            /** @description Run created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateRunResponse"];
                };
            };
        };
    };
    get_run: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description run id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStatusResponse"];
                };
            };
            /** @description no such run */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_events: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description run id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream of the run's event log */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    approve_gate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description run id */
                id: string;
                /** @description gate step id */
                step: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description gate released */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description no such run or gate */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_logs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description run id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream of step log output */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    restart_step: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description run id */
                id: string;
                /** @description step id */
                step: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description restart accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description no such run or step */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
