/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/.well-known/jwks.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OIDC issuer JWKS (ADR-0015) */
        get: operations["jwks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/.well-known/openid-configuration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OIDC discovery (ADR-0015) */
        get: operations["openid_configuration"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness: process up (ADR-0053) */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Prometheus gauges (ADR-0053) */
        get: operations["metrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness: DB + object store reachable (ADR-0053) */
        get: operations["readyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Finish the browser OAuth flow (ADR-0049) */
        get: operations["oauth_callback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Begin the browser OAuth flow (ADR-0049) */
        get: operations["oauth_login_redirect"];
        put?: never;
        /** Exchange an OAuth credential for a session (API/CLI, ADR-0049) */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the session (ADR-0049) */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Return the current authenticated principal. In dev (auth disabled) this is
         *     the synthetic Owner.
         */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orgs/{org}/bindings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List an org's role bindings (ADR-0049) */
        get: operations["list_bindings"];
        /** Natively grant a role (ADR-0049) */
        put: operations["put_binding"];
        post?: never;
        /** Natively revoke a role - a durable tombstone (ADR-0049) */
        delete: operations["delete_binding"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/repos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the registered projects (ADR-0046 registry — what the dashboard's
         *     repo cards render). Scoped: global roles see all; otherwise only orgs/
         *     projects the caller's bindings grant Read on.
         */
        get: operations["list_projects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/repos/{org}/{repo}/bindings/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Seed bindings from forge permissions (ADR-0049) */
        post: operations["import_bindings"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/repos/{org}/{repo}/dispatch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dispatch a named repo pipeline at a ref (ADR-0043 "World B"). Authorized as a
         *     write (like [`create_run`]); a dispatch is a *trigger*, so a deploy pipeline
         *     still hits its Environment's protection rules at admission. Returns the new
         *     run id (mirrors [`CreateRunResponse`]); creates **no** run on any error.
         */
        post: operations["dispatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/repos/{org}/{repo}/environments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a repo's environments */
        get: operations["list_environments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/repos/{org}/{repo}/environments/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One environment's protection rules */
        get: operations["get_environment"];
        /** Create/replace a protected environment (ADR-0024/0037) */
        put: operations["put_environment"];
        post?: never;
        /** Delete an environment (idempotent) */
        delete: operations["delete_environment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/repos/{org}/{repo}/environments/{name}/deployments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** An environment's deployment history (ADR-0037) */
        get: operations["list_deployments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/repos/{org}/{repo}/pipelines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The manually-dispatchable catalog at a ref (ADR-0043 §4). Resolves `ref` to a
         *     concrete commit (echoed back), enumerates every `.scarab/*.{yaml,yml}` at it
         *     (direct children only — `.scarab/lib/**` is excluded, mirroring webhook
         *     discovery), and reports each pipeline's `manual`/`api` opt-in from a
         *     **lightweight `on:`-only parse** (no `invoke:` pre-fetch, no full compile —
         *     that cost is deferred to the on-selection interface read). A single file that
         *     fails to parse is flagged with an `error` rather than failing the whole list;
         *     an absent `.scarab/` yields an empty catalog, not an error. Read capability.
         */
        get: operations["list_pipelines"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/repos/{org}/{repo}/pipelines/{name}/interface": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The compiled, typed launch-parameter schema for one selected pipeline
         *     (ADR-0043 §4) — the on-selection describe. Resolves `ref` to a concrete
         *     commit (echoed back), reads the named pipeline there, and **fully compiles**
         *     it (reusing the shared [`prefetch_libs_and_compile`] — this is where the
         *     lib-prefetch cost is justified), returning `interface.inputs` as typed
         *     [`ParamSpec`](scarab_pipeline::ParamSpec)s. The response is a pure function of
         *     the compiled IR — the same path dispatch rides, no parallel parser — so a
         *     compile error surfaces as a structured 4xx (never a 500), identical to
         *     dispatch. Read capability.
         */
        get: operations["pipeline_interface"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/repos/{org}/{repo}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A repo's most recent runs, newest first (ADR-0046) — the dashboard's per-repo
         *     history and pass/fail chart source. Scoped to the repo's tenant.
         */
        get: operations["list_repo_runs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/repos/{org}/{repo}/secrets/matrix": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The secret parity matrix (ADR-0037) - names + status, never values */
        get: operations["secret_matrix"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The most recent runs, newest first — the runs-list view (ADR-0013, 0028). */
        get: operations["list_runs"];
        put?: never;
        /** Create and durably persist a new run from an inline pipeline. */
        post: operations["create_run"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current status of a run and its steps. */
        get: operations["get_run"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{id}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a run's artifacts of record (ADR-0052). Read at the run's tenant. */
        get: operations["list_artifacts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{id}/artifacts/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download one artifact's bytes (ADR-0052). Streams through the server (a
         *     presigned-URL fast path can replace this when the store backend supports
         *     signing). Read at the run's tenant; immutable content.
         */
        get: operations["download_artifact"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel a run (ADR-0054): drive its non-terminal steps and the run to
         *     `Cancelled` durably and enqueue the Pod-teardown intent the driver
         *     executes (SIGTERM + grace via the backend). Idempotent — cancelling a
         *     terminal run is a 409; an unknown run is a 404.
         */
        post: operations["cancel_run"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Server-Sent-Events tail of the run's append-only event log — the status
         *     timeline (ADR-0013): RunCreated, transitions, attempt start/finish.
         */
        get: operations["get_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{id}/gates/{step}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve a `manual` gate (ADR-0008, 0037). The authenticated principal's
         *     approval is recorded on the event log (append-only, idempotent). For a
         *     **deploy** run (one with a target environment), the gate is released only
         *     once the accumulated approvers satisfy the environment's protection rules
         *     (`admits`); on release the deployment is written to history. A plain gate (no
         *     environment) releases on the first approval. Authz'd as a write.
         */
        post: operations["approve_gate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{id}/gates/{step}/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Release an **external** gate by presenting its token (ADR-0034) — the path an
         *     outside system (a deploy webhook, a change-management tool) uses instead of an
         *     interactive approval. The token is `HMAC-SHA256(secret, "{run}:{step}")`
         *     (`sha256=<hex>`), verified in constant time; no per-gate storage. The endpoint
         *     is 404 when no token secret is configured, and only releases gates of kind
         *     `external` (manual gates stay approval-only).
         */
        post: operations["release_gate_external"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{id}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Server-Sent-Events of step **log bodies** (ADR-0013): replays every
         *     committed chunk (decompressed from the object store, indexed by Postgres
         *     offsets), then — while the run is still going — live-tails new chunks via the
         *     log pipeline's broadcast. A terminal run yields the full log and closes.
         */
        get: operations["get_logs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{id}/steps/{step}/restart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restart a step and its transitive descendants (ADR-0027 smart invalidation):
         *     the target and every step depending on it are re-armed and re-run in
         *     dependency order; siblings and ancestors are left as-is.
         */
        post: operations["restart_step"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{id}/steps/{step}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest a step's named results (ADR-0040/0042): the trusted per-Pod egress
         *     sidecar POSTs `{ name: value, … }` here, authenticated by a fence-scoped
         *     token, and the control plane persists them to `step_runs.results`. The
         *     untrusted step never calls this — only the sidecar holds the token.
         * @description 404 when no token secret is configured; 401 on a bad/missing token; 404 for
         *     an unknown step; 413 for an over-large body. The write is idempotent on the
         *     fence (a re-drive overwrites deterministically, ADR-0021).
         */
        post: operations["ingest_step_results"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/secrets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the secret **names** at a scope (ADR-0014) — never the values. */
        get: operations["list_secrets"];
        put?: never;
        /**
         * Define (or overwrite) a secret at a scope (ADR-0014). The value is stored
         *     envelope-encrypted and is **never** returned by any endpoint. Administering
         *     secrets requires the Administer capability.
         */
        post: operations["put_secret"];
        /** Delete a secret at a scope (ADR-0014). Idempotent. */
        delete: operations["delete_secret"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/forgejo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Forgejo webhook ingest (HMAC-verified, ADR-0046) */
        post: operations["forgejo_webhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/github": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** GitHub webhook ingest (HMAC-verified, ADR-0046) */
        post: operations["github_webhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description One artifact in a run's list (ADR-0052). */
        ArtifactDto: {
            content_type: string;
            name: string;
            /** Format: int64 */
            size: number;
        };
        BindingDto: {
            /** @description Empty = org-scoped. */
            project: string;
            role: string;
            subject: string;
        };
        /**
         * @description One pipeline in the dispatch catalog: its selection `name` and whether it
         *     opts into `manual` / `api` dispatch (its `on:` includes that trigger).
         */
        CatalogEntry: {
            /** @description This pipeline declares `on: api` — its programmatic dispatch sibling. */
            api: boolean;
            /**
             * @description Set when this single file failed to parse — the rest of the catalog still
             *     lists (a broken sibling does not fail the whole listing, ADR-0043 §4).
             */
            error?: string | null;
            /** @description This pipeline declares `on: manual` — it appears in the human catalog. */
            manual: boolean;
            /**
             * @description The bare selection name (e.g. `deploy`) — what a describe/dispatch call
             *     passes as `pipeline`.
             */
            name: string;
        };
        /**
         * @description `POST /v1/runs` body: an inline pipeline to run immediately, plus any launch
         *     parameters (ADR-0043) declared by the pipeline's `interface`.
         */
        CreateRunRequest: {
            /**
             * @description Supplied launch parameters, `name → value` (ADR-0043). Resolved against
             *     `pipeline.interface.inputs` at creation: coerced to the declared types,
             *     defaults applied, validated fail-closed. Absent = none supplied.
             */
            params?: Record<string, never>;
            pipeline: components["schemas"]["PipelineDto"];
        };
        CreateRunResponse: {
            id: string;
            status: string;
        };
        /**
         * @description Which trigger a dispatch opts into: a human [`Manual`](DispatchKind::Manual)
         *     dispatch (the default) or its programmatic [`Api`](DispatchKind::Api) sibling
         *     (ADR-0043 §4). The named pipeline must declare the matching `on:` trigger to
         *     be dispatchable.
         * @enum {string}
         */
        DispatchKind: "manual" | "api";
        /**
         * @description `POST /v1/repos/{org}/{repo}/dispatch` body: dispatch a **named** pipeline at
         *     a `ref`, supplying its declared launch parameters (ADR-0043 "World B"). Unlike
         *     the inline `POST /v1/runs` escape hatch, this rides the read-at-ref → compile
         *     → admission machinery — a dispatched deploy hits Environment governance.
         */
        DispatchRequest: {
            /**
             * @description Which trigger to dispatch: `manual` (default) or `api`. The pipeline must
             *     declare the matching `on:`.
             */
            kind?: components["schemas"]["DispatchKind"];
            /**
             * @description Supplied launch parameters, `name → value` (ADR-0043). Resolved against
             *     the pipeline's `interface.inputs` at the resolved commit: coerced,
             *     defaulted, validated fail-closed. Absent = none supplied.
             */
            params?: Record<string, never>;
            /**
             * @description The pipeline to run — a `.scarab` name (e.g. `deploy`) or a full
             *     `.scarab/*.yaml` path.
             */
            pipeline: string;
            /**
             * @description The ref to dispatch at (branch/tag/sha). Resolved to a concrete commit;
             *     the run pins to that commit.
             */
            ref: string;
        };
        LoginResponse: {
            /**
             * @description The session's CSRF token — browsers echo it in `x-csrf-token` on every
             *     mutation (also delivered as the readable `scarab_csrf` cookie).
             */
            csrf: string;
            session: string;
            subject: string;
        };
        /** @description The authenticated principal (ADR-0049) — powers the UI's identity menu. */
        MeResponse: {
            /** @description Human display name, when the identity provides one. */
            display_name?: string | null;
            /** @description The principal's Scarab-native roles (e.g. `["Owner"]`). */
            roles: string[];
            /** @description Stable, forge-agnostic identity subject. */
            subject: string;
        };
        /**
         * @description `GET /v1/repos/{org}/{repo}/pipelines?ref=` body: the manually-dispatchable
         *     catalog at a ref (ADR-0043 §4). Lightweight — each entry is an `on:`-only
         *     read, not a full compile. `sha` is the ref resolved to a concrete commit.
         */
        PipelineCatalogResponse: {
            /**
             * @description Every `.scarab/*.{yaml,yml}` at the commit (excluding `.scarab/lib/**`),
             *     path-sorted.
             */
            pipelines: components["schemas"]["CatalogEntry"][];
            /**
             * @description The ref resolved to a concrete commit — the catalog reflects this exact
             *     commit, and a subsequent describe/dispatch should pin to it.
             */
            sha: string;
        };
        /** @description The inline pipeline (IR subset). */
        PipelineDto: {
            /**
             * Format: int32
             * @description Opt-in run budget in seconds (ADR-0047): the run fails once its
             *     **active** time (gate-suspended time excluded) exceeds this. No default.
             */
            budget?: number | null;
            /**
             * @description The pipeline's launch/reuse interface (ADR-0038, 0043) — its declared
             *     typed parameters (`inputs`) and exposed outputs. Carried as the pure
             *     `scarab_pipeline::Interface` (opaque object in the schema; the pure crate
             *     cannot derive `ToSchema`). Absent = no parameters.
             */
            interface?: Record<string, never>;
            /**
             * Format: int32
             * @description IR schema version (ADR-0022).
             */
            ir_version: number;
            steps: components["schemas"]["StepDto"][];
        };
        /**
         * @description `GET /v1/repos/{org}/{repo}/pipelines/{name}/interface?ref=` body: the
         *     compiled, typed launch-parameter schema for ONE selected pipeline (ADR-0043
         *     §4). A pure function of the compiled IR — the same compile path dispatch
         *     rides — so the form and the run validate against byte-identical specs.
         */
        PipelineInterfaceResponse: {
            /** @description This pipeline opts into `api` dispatch (`on: api`). */
            api: boolean;
            /**
             * @description The declared typed launch parameters (name, type, required, default,
             *     options, validate, description) — the compiled `interface.inputs`.
             */
            inputs: Record<string, never>[];
            /** @description This pipeline opts into `manual` dispatch (`on: manual`). */
            manual: boolean;
            /**
             * @description The ref resolved to a concrete commit — the interface reflects this exact
             *     commit; a subsequent dispatch should pin to it.
             */
            sha: string;
        };
        /** @description One registered project (governed repo, ADR-0046) in the repos list. */
        ProjectDto: {
            /**
             * Format: int64
             * @description Epoch millis of the project's most recent run, or `null` if it has never
             *     run — the dashboard's recency signal (ADR-0046). The domain carries no
             *     push/created_at yet, so never-run repos have no ordering key here.
             */
            last_run_at?: number | null;
            name: string;
            org: string;
            /** @description The forge coordinate backing it (1:1 in v1). */
            owner: string;
            project: string;
        };
        /**
         * @description `POST /v1/secrets` body: define (or overwrite) a secret at a scope. The
         *     `value` is **write-only** — no endpoint ever returns it.
         */
        PutSecretRequest: {
            /** @description Environment, for an environment-scoped secret (requires `repo`). */
            environment?: string | null;
            /** @description Secret name (the key steps reference). */
            name: string;
            /** @description Owning org (required). */
            org: string;
            /** @description Repo, for a repo- or environment-scoped secret. */
            repo?: string | null;
            /** @description Secret value — stored envelope-encrypted, never returned. */
            value: string;
        };
        /** @description `GET /v1/runs` body: the most recent runs, newest first. */
        RunListResponse: {
            runs: components["schemas"]["RunSummaryDto"][];
        };
        RunStatusResponse: {
            id: string;
            /**
             * @description The run's frozen launch parameters, `name → typed value` (ADR-0043 §5).
             *     A run-level constant resolved once at creation; non-secret by contract
             *     (§6), so safe to expose. Empty when the run took none. Lets the UI's
             *     re-run flow pre-fill the form from the prior run's params.
             */
            params?: Record<string, never>;
            status: string;
            steps: components["schemas"]["StepStatusDto"][];
        };
        /**
         * @description One run in the list view: identity, status, creation time (epoch millis),
         *     and — when the run was stamped at creation (ADR-0049) — its owning tenant.
         */
        RunSummaryDto: {
            /** Format: int64 */
            created_at: number;
            id: string;
            /** @description The owning org, if the run is tenanted (trigger-created). */
            org?: string | null;
            /** @description The owning project (repo name), if tenanted. */
            project?: string | null;
            status: string;
        };
        /**
         * @description `GET /v1/secrets` body: the secret **names** at a scope. Values are never
         *     listed.
         */
        SecretListResponse: {
            names: string[];
        };
        /**
         * @description `GET /v1/repos/{org}/{repo}/secrets/matrix` body: the advisory parity view
         *     (ADR-0037). For each secret key, its **effective** status per environment
         *     after inheritance — never a value. `unset` where the key resolves to nothing.
         */
        SecretMatrix: {
            /** @description The repo's environments, in the order the columns should render. */
            environments: string[];
            keys: components["schemas"]["SecretMatrixRow"][];
        };
        SecretMatrixRow: {
            key: string;
            /** @description `environment name -> "set" | "inherited" | "unset"`. */
            status: {
                [key: string]: string;
            };
        };
        /** @description One step (IR subset): the step contract is an OCI `image` + `command`. */
        StepDto: {
            command?: string[];
            env?: {
                [key: string]: string;
            };
            id: string;
            image: string;
            needs?: string[];
            /**
             * @description Opt-in retry policy `{on, max}` (ADR-0047). ⚠ At-least-once: retry
             *     re-runs the whole step at-least-once; enable only if the step is
             *     idempotent or fenced against a cooperating sink. Never-started infra
             *     failures auto-retry regardless.
             */
            retry?: Record<string, never>;
            /** @description Secret keys to resolve and inject at launch (ADR-0037). */
            secrets?: string[];
            /**
             * @description Privilege escalation requested above the hardened baseline (ADR-0039).
             *     On an inline API run only the self-service `run_as_root` grant is admitted
             *     (it stays inside the sandbox); governed grants (add-capabilities /
             *     privileged) require a target Environment and are rejected fail-closed.
             */
            security?: Record<string, never>;
            /**
             * Format: int32
             * @description Per-step execution deadline in seconds (ADR-0047). Absent = the global
             *     default (1h). Exceeding it is a `Timeout` failure.
             */
            timeout?: number | null;
        };
        StepStatusDto: {
            attempts: number;
            /**
             * @description `manual`/`timer`/`external` if this step is a gate (ADR-0008), else absent.
             *     Gates launch no pod and suspend the run until released.
             */
            gate?: string | null;
            id: string;
            /**
             * @description Upstream step ids this step depends on — the DAG in-edges (ADR-0006). The
             *     UI folds these into the run's graph view.
             */
            needs?: string[];
            status: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    jwks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description the signing keys */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description issuer disabled */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    openid_configuration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description the discovery document */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description issuer disabled */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    metrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Prometheus text exposition */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description a dependency is unreachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    oauth_callback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description session + CSRF cookies set; redirect to / */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description state mismatch or bad code */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    oauth_login_redirect: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description redirect to the provider with a state cookie */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description OAuth not configured */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description bad credential */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description login not configured */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description session revoked; cookies expired */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_bindings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BindingDto"][];
                };
            };
            /** @description not an org admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    put_binding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description granted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_binding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_projects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDto"][];
                };
            };
        };
    };
    import_bindings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BindingDto"][];
                };
            };
        };
    };
    dispatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description repo owner */
                org: string;
                /** @description repo name */
                repo: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DispatchRequest"];
            };
        };
        responses: {
            /** @description Run created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateRunResponse"];
                };
            };
        };
    };
    list_environments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description the environments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_environment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description the environment */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description unknown */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    put_environment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description stored */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_environment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_deployments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description most recent first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_pipelines: {
        parameters: {
            query?: {
                /** @description ref to read the config at (default HEAD) */
                ref?: string;
            };
            header?: never;
            path: {
                /** @description repo owner */
                org: string;
                /** @description repo name */
                repo: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description dispatch catalog at the resolved commit */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineCatalogResponse"];
                };
            };
        };
    };
    pipeline_interface: {
        parameters: {
            query?: {
                /** @description ref to read the config at (default HEAD) */
                ref?: string;
            };
            header?: never;
            path: {
                /** @description repo owner */
                org: string;
                /** @description repo name */
                repo: string;
                /** @description pipeline name (bare, e.g. `deploy`) */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description the compiled typed parameter schema */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineInterfaceResponse"];
                };
            };
            /** @description the pipeline failed to compile (structured diagnostic) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description no pipeline by that name at the ref */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_repo_runs: {
        parameters: {
            query?: {
                /** @description max runs (default 50, capped 200) */
                limit?: number;
            };
            header?: never;
            path: {
                /** @description org slug */
                org: string;
                /** @description project (repo) name */
                repo: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunListResponse"];
                };
            };
        };
    };
    secret_matrix: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecretMatrix"];
                };
            };
        };
    };
    list_runs: {
        parameters: {
            query?: {
                /** @description max runs to return (default 50, max 200) */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunListResponse"];
                };
            };
        };
    };
    create_run: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRunRequest"];
            };
        };
        responses: {
            /** @description Run created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateRunResponse"];
                };
            };
        };
    };
    get_run: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description run id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStatusResponse"];
                };
            };
            /** @description no such run */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_artifacts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description run id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactDto"][];
                };
            };
            /** @description no such run */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    download_artifact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description run id */
                id: string;
                /** @description artifact name (may contain slashes) */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description the artifact bytes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description no such artifact */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cancel_run: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description run id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description cancellation recorded; Pods tear down asynchronously */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description no such run */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description run already terminal */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_events: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description run id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream of the run's event log */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    approve_gate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description run id */
                id: string;
                /** @description gate step id */
                step: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description approval recorded (released or awaiting more approvals) */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description no such run or gate */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    release_gate_external: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description run id */
                id: string;
                /** @description gate step id */
                step: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description gate released */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description bad or missing token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description no such external gate, or token release disabled */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_logs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description run id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream of step log output */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    restart_step: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description run id */
                id: string;
                /** @description step id */
                step: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description restart accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description no such run or step */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ingest_step_results: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description run id */
                id: string;
                /** @description step id */
                step: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description results recorded */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description bad or missing token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description no such step, or results ingest disabled */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_secrets: {
        parameters: {
            query: {
                /** @description owning org */
                org: string;
                /** @description repo (repo/env scope) */
                repo?: string;
                /** @description environment (env scope) */
                environment?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecretListResponse"];
                };
            };
            /** @description secrets not configured */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    put_secret: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PutSecretRequest"];
            };
        };
        responses: {
            /** @description secret stored */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description secrets not configured */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_secret: {
        parameters: {
            query: {
                /** @description owning org */
                org: string;
                /** @description repo (repo/env scope) */
                repo?: string;
                /** @description environment (env scope) */
                environment?: string;
                /** @description secret name to delete */
                name: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description deleted (idempotent) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description secrets not configured */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    forgejo_webhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description delivery accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description bad signature */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    github_webhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description delivery accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description bad signature */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
