/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/repos/{org}/{repo}/dispatch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dispatch a named repo pipeline at a ref (ADR-0043 "World B"). Authorized as a
         *     write (like [`create_run`]); a dispatch is a *trigger*, so a deploy pipeline
         *     still hits its Environment's protection rules at admission. Returns the new
         *     run id (mirrors [`CreateRunResponse`]); creates **no** run on any error.
         */
        post: operations["dispatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/repos/{org}/{repo}/pipelines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The manually-dispatchable catalog at a ref (ADR-0043 §4). Resolves `ref` to a
         *     concrete commit (echoed back), enumerates every `.scarab/*.{yaml,yml}` at it
         *     (direct children only — `.scarab/lib/**` is excluded, mirroring webhook
         *     discovery), and reports each pipeline's `manual`/`api` opt-in from a
         *     **lightweight `on:`-only parse** (no `invoke:` pre-fetch, no full compile —
         *     that cost is deferred to the on-selection interface read). A single file that
         *     fails to parse is flagged with an `error` rather than failing the whole list;
         *     an absent `.scarab/` yields an empty catalog, not an error. Read capability.
         */
        get: operations["list_pipelines"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/repos/{org}/{repo}/pipelines/{name}/interface": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The compiled, typed launch-parameter schema for one selected pipeline
         *     (ADR-0043 §4) — the on-selection describe. Resolves `ref` to a concrete
         *     commit (echoed back), reads the named pipeline there, and **fully compiles**
         *     it (reusing the shared [`prefetch_libs_and_compile`] — this is where the
         *     lib-prefetch cost is justified), returning `interface.inputs` as typed
         *     [`ParamSpec`](scarab_pipeline::ParamSpec)s. The response is a pure function of
         *     the compiled IR — the same path dispatch rides, no parallel parser — so a
         *     compile error surfaces as a structured 4xx (never a 500), identical to
         *     dispatch. Read capability.
         */
        get: operations["pipeline_interface"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The most recent runs, newest first — the runs-list view (ADR-0013, 0028). */
        get: operations["list_runs"];
        put?: never;
        /** Create and durably persist a new run from an inline pipeline. */
        post: operations["create_run"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current status of a run and its steps. */
        get: operations["get_run"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Server-Sent-Events tail of the run's append-only event log — the status
         *     timeline (ADR-0013): RunCreated, transitions, attempt start/finish.
         */
        get: operations["get_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{id}/gates/{step}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve a `manual` gate (ADR-0008, 0037). The authenticated principal's
         *     approval is recorded on the event log (append-only, idempotent). For a
         *     **deploy** run (one with a target environment), the gate is released only
         *     once the accumulated approvers satisfy the environment's protection rules
         *     (`admits`); on release the deployment is written to history. A plain gate (no
         *     environment) releases on the first approval. Authz'd as a write.
         */
        post: operations["approve_gate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{id}/gates/{step}/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Release an **external** gate by presenting its token (ADR-0034) — the path an
         *     outside system (a deploy webhook, a change-management tool) uses instead of an
         *     interactive approval. The token is `HMAC-SHA256(secret, "{run}:{step}")`
         *     (`sha256=<hex>`), verified in constant time; no per-gate storage. The endpoint
         *     is 404 when no token secret is configured, and only releases gates of kind
         *     `external` (manual gates stay approval-only).
         */
        post: operations["release_gate_external"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{id}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Server-Sent-Events of step **log bodies** (ADR-0013): replays every
         *     committed chunk (decompressed from the object store, indexed by Postgres
         *     offsets), then — while the run is still going — live-tails new chunks via the
         *     log pipeline's broadcast. A terminal run yields the full log and closes.
         */
        get: operations["get_logs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{id}/steps/{step}/restart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restart a step and its transitive descendants (ADR-0027 smart invalidation):
         *     the target and every step depending on it are re-armed and re-run in
         *     dependency order; siblings and ancestors are left as-is.
         */
        post: operations["restart_step"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/secrets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the secret **names** at a scope (ADR-0014) — never the values. */
        get: operations["list_secrets"];
        put?: never;
        /**
         * Define (or overwrite) a secret at a scope (ADR-0014). The value is stored
         *     envelope-encrypted and is **never** returned by any endpoint. Administering
         *     secrets requires the Administer capability.
         */
        post: operations["put_secret"];
        /** Delete a secret at a scope (ADR-0014). Idempotent. */
        delete: operations["delete_secret"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description One pipeline in the dispatch catalog: its selection `name` and whether it
         *     opts into `manual` / `api` dispatch (its `on:` includes that trigger).
         */
        CatalogEntry: {
            /** @description This pipeline declares `on: api` — its programmatic dispatch sibling. */
            api: boolean;
            /**
             * @description Set when this single file failed to parse — the rest of the catalog still
             *     lists (a broken sibling does not fail the whole listing, ADR-0043 §4).
             */
            error?: string | null;
            /** @description This pipeline declares `on: manual` — it appears in the human catalog. */
            manual: boolean;
            /**
             * @description The bare selection name (e.g. `deploy`) — what a describe/dispatch call
             *     passes as `pipeline`.
             */
            name: string;
        };
        /**
         * @description `POST /v1/runs` body: an inline pipeline to run immediately, plus any launch
         *     parameters (ADR-0043) declared by the pipeline's `interface`.
         */
        CreateRunRequest: {
            /**
             * @description Supplied launch parameters, `name → value` (ADR-0043). Resolved against
             *     `pipeline.interface.inputs` at creation: coerced to the declared types,
             *     defaults applied, validated fail-closed. Absent = none supplied.
             */
            params?: Record<string, never>;
            pipeline: components["schemas"]["PipelineDto"];
        };
        CreateRunResponse: {
            id: string;
            status: string;
        };
        /**
         * @description Which trigger a dispatch opts into: a human [`Manual`](DispatchKind::Manual)
         *     dispatch (the default) or its programmatic [`Api`](DispatchKind::Api) sibling
         *     (ADR-0043 §4). The named pipeline must declare the matching `on:` trigger to
         *     be dispatchable.
         * @enum {string}
         */
        DispatchKind: "manual" | "api";
        /**
         * @description `POST /v1/repos/{org}/{repo}/dispatch` body: dispatch a **named** pipeline at
         *     a `ref`, supplying its declared launch parameters (ADR-0043 "World B"). Unlike
         *     the inline `POST /v1/runs` escape hatch, this rides the read-at-ref → compile
         *     → admission machinery — a dispatched deploy hits Environment governance.
         */
        DispatchRequest: {
            /**
             * @description Which trigger to dispatch: `manual` (default) or `api`. The pipeline must
             *     declare the matching `on:`.
             */
            kind?: components["schemas"]["DispatchKind"];
            /**
             * @description Supplied launch parameters, `name → value` (ADR-0043). Resolved against
             *     the pipeline's `interface.inputs` at the resolved commit: coerced,
             *     defaulted, validated fail-closed. Absent = none supplied.
             */
            params?: Record<string, never>;
            /**
             * @description The pipeline to run — a `.scarab` name (e.g. `deploy`) or a full
             *     `.scarab/*.yaml` path.
             */
            pipeline: string;
            /**
             * @description The ref to dispatch at (branch/tag/sha). Resolved to a concrete commit;
             *     the run pins to that commit.
             */
            ref: string;
        };
        /**
         * @description `GET /v1/repos/{org}/{repo}/pipelines?ref=` body: the manually-dispatchable
         *     catalog at a ref (ADR-0043 §4). Lightweight — each entry is an `on:`-only
         *     read, not a full compile. `sha` is the ref resolved to a concrete commit.
         */
        PipelineCatalogResponse: {
            /**
             * @description Every `.scarab/*.{yaml,yml}` at the commit (excluding `.scarab/lib/**`),
             *     path-sorted.
             */
            pipelines: components["schemas"]["CatalogEntry"][];
            /**
             * @description The ref resolved to a concrete commit — the catalog reflects this exact
             *     commit, and a subsequent describe/dispatch should pin to it.
             */
            sha: string;
        };
        /** @description The inline pipeline (IR subset). */
        PipelineDto: {
            /**
             * @description The pipeline's launch/reuse interface (ADR-0038, 0043) — its declared
             *     typed parameters (`inputs`) and exposed outputs. Carried as the pure
             *     `scarab_pipeline::Interface` (opaque object in the schema; the pure crate
             *     cannot derive `ToSchema`). Absent = no parameters.
             */
            interface?: Record<string, never>;
            /**
             * Format: int32
             * @description IR schema version (ADR-0022).
             */
            ir_version: number;
            steps: components["schemas"]["StepDto"][];
        };
        /**
         * @description `GET /v1/repos/{org}/{repo}/pipelines/{name}/interface?ref=` body: the
         *     compiled, typed launch-parameter schema for ONE selected pipeline (ADR-0043
         *     §4). A pure function of the compiled IR — the same compile path dispatch
         *     rides — so the form and the run validate against byte-identical specs.
         */
        PipelineInterfaceResponse: {
            /** @description This pipeline opts into `api` dispatch (`on: api`). */
            api: boolean;
            /**
             * @description The declared typed launch parameters (name, type, required, default,
             *     options, validate, description) — the compiled `interface.inputs`.
             */
            inputs: Record<string, never>[];
            /** @description This pipeline opts into `manual` dispatch (`on: manual`). */
            manual: boolean;
            /**
             * @description The ref resolved to a concrete commit — the interface reflects this exact
             *     commit; a subsequent dispatch should pin to it.
             */
            sha: string;
        };
        /**
         * @description `POST /v1/secrets` body: define (or overwrite) a secret at a scope. The
         *     `value` is **write-only** — no endpoint ever returns it.
         */
        PutSecretRequest: {
            /** @description Environment, for an environment-scoped secret (requires `repo`). */
            environment?: string | null;
            /** @description Secret name (the key steps reference). */
            name: string;
            /** @description Owning org (required). */
            org: string;
            /** @description Repo, for a repo- or environment-scoped secret. */
            repo?: string | null;
            /** @description Secret value — stored envelope-encrypted, never returned. */
            value: string;
        };
        /** @description `GET /v1/runs` body: the most recent runs, newest first. */
        RunListResponse: {
            runs: components["schemas"]["RunSummaryDto"][];
        };
        RunStatusResponse: {
            id: string;
            /**
             * @description The run's frozen launch parameters, `name → typed value` (ADR-0043 §5).
             *     A run-level constant resolved once at creation; non-secret by contract
             *     (§6), so safe to expose. Empty when the run took none. Lets the UI's
             *     re-run flow pre-fill the form from the prior run's params.
             */
            params?: Record<string, never>;
            status: string;
            steps: components["schemas"]["StepStatusDto"][];
        };
        /** @description One run in the list view: identity, status, and creation time (epoch millis). */
        RunSummaryDto: {
            /** Format: int64 */
            created_at: number;
            id: string;
            status: string;
        };
        /**
         * @description `GET /v1/secrets` body: the secret **names** at a scope. Values are never
         *     listed.
         */
        SecretListResponse: {
            names: string[];
        };
        /** @description One step (IR subset): the step contract is an OCI `image` + `command`. */
        StepDto: {
            command?: string[];
            env?: {
                [key: string]: string;
            };
            id: string;
            image: string;
            needs?: string[];
            /** @description Secret keys to resolve and inject at launch (ADR-0037). */
            secrets?: string[];
        };
        StepStatusDto: {
            attempts: number;
            /**
             * @description `manual`/`timer`/`external` if this step is a gate (ADR-0008), else absent.
             *     Gates launch no pod and suspend the run until released.
             */
            gate?: string | null;
            id: string;
            /**
             * @description Upstream step ids this step depends on — the DAG in-edges (ADR-0006). The
             *     UI folds these into the run's graph view.
             */
            needs?: string[];
            status: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    dispatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description repo owner */
                org: string;
                /** @description repo name */
                repo: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DispatchRequest"];
            };
        };
        responses: {
            /** @description Run created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateRunResponse"];
                };
            };
        };
    };
    list_pipelines: {
        parameters: {
            query?: {
                /** @description ref to read the config at (default HEAD) */
                ref?: string;
            };
            header?: never;
            path: {
                /** @description repo owner */
                org: string;
                /** @description repo name */
                repo: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description dispatch catalog at the resolved commit */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineCatalogResponse"];
                };
            };
        };
    };
    pipeline_interface: {
        parameters: {
            query?: {
                /** @description ref to read the config at (default HEAD) */
                ref?: string;
            };
            header?: never;
            path: {
                /** @description repo owner */
                org: string;
                /** @description repo name */
                repo: string;
                /** @description pipeline name (bare, e.g. `deploy`) */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description the compiled typed parameter schema */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineInterfaceResponse"];
                };
            };
            /** @description the pipeline failed to compile (structured diagnostic) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description no pipeline by that name at the ref */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_runs: {
        parameters: {
            query?: {
                /** @description max runs to return (default 50, max 200) */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunListResponse"];
                };
            };
        };
    };
    create_run: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRunRequest"];
            };
        };
        responses: {
            /** @description Run created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateRunResponse"];
                };
            };
        };
    };
    get_run: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description run id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStatusResponse"];
                };
            };
            /** @description no such run */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_events: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description run id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream of the run's event log */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    approve_gate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description run id */
                id: string;
                /** @description gate step id */
                step: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description approval recorded (released or awaiting more approvals) */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description no such run or gate */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    release_gate_external: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description run id */
                id: string;
                /** @description gate step id */
                step: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description gate released */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description bad or missing token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description no such external gate, or token release disabled */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_logs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description run id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream of step log output */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    restart_step: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description run id */
                id: string;
                /** @description step id */
                step: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description restart accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description no such run or step */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_secrets: {
        parameters: {
            query: {
                /** @description owning org */
                org: string;
                /** @description repo (repo/env scope) */
                repo?: string;
                /** @description environment (env scope) */
                environment?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecretListResponse"];
                };
            };
            /** @description secrets not configured */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    put_secret: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PutSecretRequest"];
            };
        };
        responses: {
            /** @description secret stored */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description secrets not configured */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_secret: {
        parameters: {
            query: {
                /** @description owning org */
                org: string;
                /** @description repo (repo/env scope) */
                repo?: string;
                /** @description environment (env scope) */
                environment?: string;
                /** @description secret name to delete */
                name: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description deleted (idempotent) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description secrets not configured */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
