// Produce a tagged copy of the canonical OpenAPI spec for starlight-openapi.
//
// The server's spec (../../openapi.json, generated by utoipa) ships with NO
// operation tags. starlight-openapi groups operations — and generates a page
// per operation — from tags; an untagged spec renders only a bare overview
// (no operation pages at all). So we derive a tag per operation from its path
// and write a GITIGNORED tagged copy (openapi.gen.json) that the plugin reads.
//
// This does NOT mutate the canonical openapi.json (the source of truth stays
// tag-free). The proper long-term fix is to add tags at the utoipa source so
// this step can be dropped — tracked separately.
//
// Runs as part of `gen` (predev/prebuild), mirroring sync-content.mjs.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '../../..'); // ui/scarab-docs-ui/scripts -> repo root
const src = resolve(repoRoot, 'openapi.json');
const out = resolve(here, '..', 'openapi.gen.json');

// Ordered rules: first match wins. Grouping is by path so it stays stable as
// operations are added. Keep group names human and few.
const RULES = [
  [/^\/webhooks\//, 'Webhooks'],
  [/^\/\.well-known\/|\/auth\/|\/me$|login|logout|oauth|oidc|jwks|openid/i, 'Auth & Identity'],
  [/^\/(healthz|readyz|metrics)$/, 'System'],
  [/\/environments/, 'Environments'],
  [/\/secrets|secret/i, 'Secrets'],
  [/\/runs|\/steps?\/|\/gate|\/artifacts?|\/workspace|\/events|\/logs|\/results/i, 'Runs'],
  [/\/repos|\/projects|\/pipelines|\/refs|\/dispatch|\/interface|binding/i, 'Repositories'],
];

// Display order for the sidebar groups (top-level `tags`).
const ORDER = ['Runs', 'Repositories', 'Environments', 'Secrets', 'Webhooks', 'Auth & Identity', 'System', 'Other'];

const METHODS = ['get', 'post', 'put', 'delete', 'patch', 'options', 'head'];

function tagFor(path) {
  for (const [re, tag] of RULES) if (re.test(path)) return tag;
  return 'Other';
}

const spec = JSON.parse(readFileSync(src, 'utf8'));
const used = new Set();
let ops = 0;
for (const path in spec.paths) {
  for (const method in spec.paths[path]) {
    if (!METHODS.includes(method)) continue;
    const op = spec.paths[path][method];
    if (!op || typeof op !== 'object') continue;
    const tag = tagFor(path);
    op.tags = [tag];
    used.add(tag);
    ops++;
  }
}
spec.tags = ORDER.filter((t) => used.has(t)).map((name) => ({ name }));

writeFileSync(out, JSON.stringify(spec, null, 2), 'utf8');
console.log(`gen-openapi: tagged ${ops} operations across ${spec.tags.length} groups -> openapi.gen.json`);
