-- Ticket 4cf03d7 / ADR-0064 control-plane half: a Failed attempt records WHY,
-- not just which retry policy applied.
--
-- `attempts.failure` is the machine-consumed class (ADR-0047) — it decides
-- retry policy and nothing else. Until now the executor's actual diagnosis
-- ("cold tier refused: connection refused", "declared output path not
-- produced: dist/") died in an eprintln! on the control plane, so a Depot
-- outage that failed an Attempt presented as an anonymous Infra failure and a
-- contract violation as a bare Config. This column is the human-readable
-- cause, written by `set_attempt_failure` alongside the class in the same
-- UPDATE (so the two can never diverge on which attempt they describe).
--
-- Expand-contract (ADR-0022 invariant 3): NULLable, no backfill. A row written
-- before this migration simply has no recorded cause — the class was the whole
-- story then and still renders as such. Old binaries never name the column.
ALTER TABLE attempts ADD COLUMN failure_detail TEXT;
