-- Ticket 981fc6b / ADR-0064 s2: each Attempt records WHERE its output
-- workspace snapshot was durable when its verdict was granted.
--
-- `attempts.output_snapshot` says where the bytes are and `output_identity`
-- what they are (ADR-0061 s8); neither says how durable they were at the
-- moment `Succeeded` was released. Under ADR-0064 the flush gates the verdict
-- on the Depot's tier — object storage, a separate volume, or (dev-grade)
-- warm-only — and that tier is a property of the DEPLOYMENT AT THAT INSTANT,
-- not of the deployment now. This column freezes it per attempt, written by
-- `set_step_output` in the same UPDATE as the snapshot root (so the two can
-- never diverge on which attempt they describe). Wire strings: 'object' |
-- 'separate-volume' | 'warm-only'. Attempt-grain only, deliberately never
-- denormalized onto step_runs: the question it answers is historical.
--
-- Expand-contract (ADR-0022 invariant 3): NULLable, no backfill. A row
-- written before this migration — or by a backend without the stamp, or for
-- a step with no workspace — simply has no recorded tier. Old binaries never
-- name the column.
ALTER TABLE attempts ADD COLUMN output_durability TEXT;
