-- QA finding / git-bug 5120335: `concurrency_slots.group_key` is a GLOBAL
-- primary key, but it was fed the author's `concurrency.group` string verbatim
-- — so two unrelated tenants both naming their group `deploy` shared one slot
-- (cross-tenant serialization), and under `cancel-in-progress` one tenant's
-- run cancelled the other's.
--
-- The fix is in the control plane, at key CONSTRUCTION (persist_run_from_ir):
-- the stored key is now `{owner}/{repo}:{group}` — the same tenancy prefix the
-- adjacent `supersede_key` has always carried — with `inline:{group}` for
-- untenanted (repo-less) runs. The schema is unchanged; this migration only
-- records the key-format change on the column.
--
-- No backfill and no truncate, deliberately. `concurrency_slots` rows are
-- ephemeral lock state: a row exists only while its holder run is in flight,
-- is released by exact key from `runs.concurrency_group` when the holder
-- settles, and `acquire_slot` reclaims any row whose holder is terminal or
-- gone. A run in flight across this deploy stored its (unprefixed) group in
-- `runs.concurrency_group` and will acquire/release that same key
-- consistently, then the row deletes itself; new runs use prefixed keys. The
-- only effect of leaving old rows alone is a one-transition window in which a
-- pre-deploy run and a post-deploy run of the SAME tenant+group don't
-- serialize against each other — strictly less harm than a truncate, which
-- would open that same window AND drop live holders' locks.
COMMENT ON COLUMN concurrency_slots.group_key IS
    'Tenancy-scoped slot key: {owner}/{repo}:{group} (inline:{group} for repo-less runs), built at run admission — never the raw author-supplied group name (git-bug 5120335).';
